In [1]:
import numpy as np

In [2]:
# Scalar
np_arr_0D = np.array(1)
np_arr_0D, type(np_arr_0D), np_arr_0D.ndim

(array(1), numpy.ndarray, 0)

In [3]:
# Vector
np_arr_1D = np.array([1, 2, 3, 4])
np_arr_1D, type(np_arr_1D), np_arr_1D.ndim

(array([1, 2, 3, 4]), numpy.ndarray, 1)

In [4]:
# Matrix
""" np_arr_2D = np.array([ 
                      [11, 12, 13],
                      [14, 15, 16]
                    ]) """

np_arr_2D = np.array([np_arr_1D * i for i in range(1, 5)])
np_arr_2D, type(np_arr_2D), np_arr_2D.ndim, np_arr_2D.size

(array([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]]),
 numpy.ndarray,
 2,
 16)

In [5]:
# Tensor 
np_arr_3D = np.array( [ np_arr_2D * i for i in range(1, 4)] )
np_arr_3D, np_arr_3D.size, np_arr_3D.dtype

(array([[[ 1,  2,  3,  4],
         [ 2,  4,  6,  8],
         [ 3,  6,  9, 12],
         [ 4,  8, 12, 16]],
 
        [[ 2,  4,  6,  8],
         [ 4,  8, 12, 16],
         [ 6, 12, 18, 24],
         [ 8, 16, 24, 32]],
 
        [[ 3,  6,  9, 12],
         [ 6, 12, 18, 24],
         [ 9, 18, 27, 36],
         [12, 24, 36, 48]]]),
 48,
 dtype('int32'))

Create NumPy array out of Python data structure

In [12]:
import random

my_list = [random.randint(1, 101) for i in range(1, 11)]
np_list = np.array(my_list)
np_list

array([40, 13, 98, 51, 88, 21, 75, 37,  4, 15])